# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0001_programming_language'),
        ('projects', '0008_auto_20170606_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='programming_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techs.ProgrammingLanguage'),
        ),
    ]
