# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_user status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Invited'), (2, 'Accepted'), (3, 'Declined')], null=True),
        ),
    ]
