# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='shortname',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='untitled', max_length=20),
            preserve_default=False,
        ),
    ]
