# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_git'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uri',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
