# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date']},
        ),
    ]
