# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Invited'), (1, 'Accepted'), (1, 'Declined')], null=True),
        ),
    ]
