# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0015_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Invited'), (2, 'Accepted'), (3, 'Declined')], default=1, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='projectuser',
            unique_together=set([('project', 'user')]),
        ),
    ]
